-- THE BASICS OF HASKELL
-- C-C C-B: INITIALIZE HASKELL SHELL GHCI
-- C-C C-L: LOAD CURRENT FILE INTO THE SHELL
MODULE MAIN
       WHERE

IMPORT SYSTEM.IO
IMPORT DATA.CHAR(TOUPPER)
IMPORT DATA.COMPLEX
IMPORT CONTROL.MONAD
IMPORT CONTROL.CONCURRENT
IMPORT CONTROL.CONCURRENT.STM

X = 5
Y = (6, "SALUT")
Z = X * FST Y

SQUARE X = X * X

SIGNUM X = 
       IF X < 0 
         THEN -1
       ELSE IF X > 0
         THEN 1
         ELSE 0

STAIR X = 
      CASE X OF 
           0 -> 1
           1 -> 2
           2 -> 3
           _ -> 3/0

-- RETURN TYPE MUST BE THE SAME FOR THE TWO BRANCHES
ROOTS A B C = 
  LET DET = B*B - 4*A*C IN
  LET DRT = SQRT (ABS DET) IN
  IF DET >= 0 THEN
    (((-B + DRT)/(2*A)):+0, ((-B - DRT)/(2*A)):+0)
  ELSE
    ((-B/(2*A)):+(DRT/(2*A)), (-B/(2*A)):+(-DRT/(2*A)))
  
-- RECURSION
FACTORIAL 1 = 1
FACTORIAL N = N * FACTORIAL (N-1)

-- IO
CHECKIN :: IO ()
CHECKIN = DO
        PUTSTRLN "SALUT TOUT LE MONDE! COMMENT VOUS-APPELEZ VOUS?"
        VOTRE_NOM <- GETLINE
        PUTSTRLN $ "BIENVENUE A L'HASKELL, " ++ VOTRE_NOM ++ "!\N"
    
-- FILE IO
FICHIER = DO
        FIN <- OPENFILE "BASICS.HS" READMODE
        FOUT <- OPENFILE "BASICS.GEN.HS" WRITEMODE
        PROC_FICHIER FIN FOUT
        HCLOSE FIN
        HCLOSE FOUT

-- RETURN USED TO WRAP A PURE RESULT TO IO
PROC_FICHIER FIN FOUT = 
        DO INEOF <- HISEOF FIN
           IF INEOF THEN DO
             PUTSTRLN "VOUS ETES FINIS"
             RETURN ()
           ELSE DO
             LINE <- HGETLINE FIN                   
             HPUTSTRLN FOUT (MAP TOUPPER LINE)
             PROC_FICHIER FIN FOUT

-- -- SOFTWARE TRANSACTIONAL MEMORY (STM)
-- TOUCH_STM = DO SHARED <- ATOMICALLY $ NEWTVAR 0
--                BEFORE <- ATOMREAD SHARED
--                PUTSTRLN $ "BEFORE: " ++ SHOW BEFORE
--                FORKIO $ 25 `TIMESDO` (DISPVAR SHARED >> MILLISLEEP 20)
--                FORKIO $ 10 `TIMESDO` (APPV (+ 2) SHARED >> MILLISLEEP 50)
--                FORKIO $ 20 `TIMESDO` (APPV PRED SHARED >> MILLISLEEP 25)
--                MILLISLEEP 800
--                AFTER <- ATOMREAD SHARED
--                PUTSTRLN $ "AFTER: " ++ SHOW AFTER       
--                WHERE TIMESDO = REPLICATEM_
--                      MILLISLEEP = THREADDELAY . (*) 1000

MAIN = PUTSTRLN "SALUT TOUT LE MONDE"
       
